### ISSUE TITLE
White background on 2.1.17

### ISSUE THREAD

**Issue by Iris3Meow** [lovac42/Blitzkrieg#10]
![image](https://user-images.githubusercontent.com/33403306/72405339-75a11f80-3726-11ea-976b-beceef10fc9b.png)

I am still getting this issue with the latest v0.1.2.

**Comment by lovac42** [comment]
For compatibility, you will need to use the temporary version of night mode.
https://ankiweb.net/shared/info/2041427019

**Comment by Iris3Meow** [comment]
Thank you
