### ISSUE TITLE
Any interest to add a feature that we can focus in the filter bar by pressing "Alt+D"?

### ISSUE THREAD

**Issue by acgtyrant** [lovac42/Blitzkrieg#12]
"Alt+D" is a common and useful hotkey to focus in the address bar of Google Chrome and so on.

**Comment by lovac42** [comment]
Anki uses CTRL+SHIFT+R, those code are not part of the sidebar. Maybe try customize hot keys or autohot keys?

**Comment by acgtyrant** [comment]
Really? I tried "ctrl + shift + r", but it changed the focus to to the left side.

**Comment by lovac42** [comment]
Do you mean the search bar? That would be CTRL+F, click on menu GO and you'll see the list. These are not part of the same code that this addon patches, it would make a mess of thing to put them in here.

**Comment by acgtyrant** [comment]
Okay I mean the search bar and "ctrl+f" works.
