### ISSUE TITLE
iconFromRef() deprecated 

### ISSUE THREAD

**Issue by ijgnd** [lovac42/Blitzkrieg#14]
When I run anki 2.1.20 in a terminal with your addon and open the browser I get "iconFromRef() deprecated" many times over in my terminal.

&nbsp;

Background: 
- iconFromRef was removed with the commit [basic night mode support](https://github.com/ankitects/anki/commit/7dcbc7efec08ec2928523408dd9bc7bdaae03fd8) about a month ago
-  it was reintroduced with a deprecated warning one commit later with [iconFromRef() compat](https://github.com/ankitects/anki//commit/d2336f3829de89fe141522b1e9d2fab25c81279f)

&nbsp;

my fix:

change one line in [patch_sidebar.py](https://github.com/lovac42/Blitzkrieg/blob/1ceecd1a03663dba3c5248ad0cec00a7ef284074/src/blitzkrieg/patch_sidebar.py#L98) from
    
    return QVariant(self.iconFromRef(item.icon))

to

    return QVariant(theme_manager.icon_from_resources(item.icon))

and put `from aqt.theme import theme_manager` to the top. So far I haven't noticed a problem.

&nbsp;

my debug info :
  
    Anki 2.1.20 (47a1bf8b) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
    Platform: Linux
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2020-02-18 19:36:49
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Blitzkrieg II - Advanced Browser Sidebar BETA6 ['564851917', 2020-02-03T19:54, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    564851917
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    

Finally: Thank you very much for sharing this add-on.

**Comment by lovac42** [comment]
Thanks for the heads up and doing the leg work. This should be fixed.
