### ISSUE TITLE
Blitzkrieg II - Advanced Browser Sidebar [BETA6]

### ISSUE THREAD

**Issue by KvXd** [lovac42/Blitzkrieg#16]
I recently came across this problem where I **rename the tag and then it disappears** like if the name was let's say  Actions_NB  and then I rename it to  Actions_nB  
 the tag then disappears completely From Anki,  Please fix it...

**Comment by lovac42** [comment]
Thanks I'll look into this. Tag names are not case sensitive, so a quick workaround for now is to rename NB to NB_ then to nB.

**Comment by lovac42** [comment]
This should be fixed in the latest update, click on the update addon button to update to the latest version.

**Comment by KvXd** [comment]
Thank you, so much, and what is the difference between this addon and the Hierarchal tags?

**Comment by lovac42** [comment]
This works on decks, models, and favs. HT is for tags only.
