### ISSUE TITLE
Cards not being counted by Clozes

### ISSUE THREAD

**Issue by mallory1-png** [lovac42/Blitzkrieg#26]
I am on anki 2.1.35, and Blitzkrieg add on causes some of my cards to be counted by the actual number of cards rather than the number of clozes. Is there a way I can fix this or revert to an earlier version of anki that will fix this without the add on? I have tried everything I know how to do.

**Comment by lovac42** [comment]
I'm not sure I understand your question. Are those clozes generated by javascript?

It looks fine to me.
![image](https://user-images.githubusercontent.com/42665127/103595718-266d7500-4eca-11eb-9023-d33e3e42962c.png)

**Comment by mallory1-png** [comment]
I figured it out. It was a random add on that was like “count each card as only 1 card” or something. Sorry to bother you! 

Mallory Harmon
University of Mississippi Medical Center 
School of Medicine | Class of 2023
601-486-3092
