### ISSUE TITLE
why commit 8a60110 (improved zip packer security)?

### ISSUE THREAD

**Issue by ijgnd** [lovac42/Blitzkrieg#3]
This not an "issue" but I'm curious. How does the commit 8a60110 which removes ` from .main import *` from your `__init__.py` and adds `echo from .main import * >>%REPO%/__init__.py` to your build script improve the security? A short hint would be great. Thanks.

**Comment by lovac42** [comment]
It's to prevent new users using drag and drop on the src folder without using official releases on the github release page.

**Comment by ijgnd** [comment]
makes sense. Thanks for this info (and in general for sharing the add-on).
