### ISSUE TITLE
Uppercase – lowercase sorting

### ISSUE THREAD

**Issue by galantra** [lovac42/Blitzkrieg#4]
This is one of the most universally applicable add-ons and adds a lot of functionality.

I used to employ uppercase tags for subject-matter distinctions (e.g. "Economics", "Politics", "Languages::Legalese") and lowercase tags for more work-in-process related tags (e.g. "add", "redact", "leech").
In the sidebar, vanilla Anki sorts all lowercase tags behind all uppercase tags.

I would be grateful if there was an option to reenable this behaviour with Blitzkrieg.

**Comment by lovac42** [comment]
Will do.

What is VA? is it a different 2.1 or just different themes?

**Comment by galantra** [comment]
Thank you!
By vanilla, I was referring to this usage:
https://en.wikipedia.org/wiki/Vanilla_software
It is the standard, plain Anki – well in fact, I use the current 2.1.15beta1.

**Comment by lovac42** [comment]
Actually the stock settings are sorted by AaBbCc in 2.1. So you are talking about 2.0. But I do like the idea and have implemented it for the next release. You have to hold down shift key to set the option. See screenshot at main readme page.

**Comment by galantra** [comment]
Oh, I was not aware of that.
I like the implementation.
