### ISSUE TITLE
Option to Show All Cards Under Parent Tag?

### ISSUE THREAD

**Issue by krispycorn** [lovac42/Blitzkrieg#6]
Hi!

I don't know if this is an intended feature or not, but I cannot see cards with multiple tags in the parent tag. For instance if my card is labeled A::B::C. I can only see the card shown when I click on C in the browser. I would like the card to show when I select both A and B tags.

Is this at all possible to configure or setup as an option?

Thank you very much!

**Comment by lovac42** [comment]
This is the default behavior of Anki. If you want to display sub-tags, you will need to right click and select "show all". Or shift + right click on "Tags" and "Auto Show Subtags".

If you just right click or shift + right click, you will get different options for different tags, decks, models, ets...

**Comment by krispycorn** [comment]
> This is the default behavior of Anki. If you want to display sub-tags, you will need to right click and select "show all". Or shift + right click on "Tags" and "Auto Show Subtags".
> 
> If you just right click or shift + right click, you will get different options for different tags, decks, models, ets...

Yo I got what I wanted by shift + right clicking. Thank you very much!
