### ISSUE TITLE
missing "leech" tag in 2.1

### ISSUE THREAD

**Issue by ijgnd** [lovac42/Blitzkrieg#7]
First of all: Thanks for this great add-on.

Blitzkrieg seems to remove the leech tag from the sidebar.

You have at [tree.py#L79](https://github.com/lovac42/Blitzkrieg/blob/master/src/blitzkrieg/tree.py#L79):

    for t in TAGS:
        if t.lower() == "marked" or t.lower() == "leech":
            continue

The same if-loop was in the method `aqt.Browser.browser._userTagTree` for 2.0 since 2.0 put the marked and leech tag prominently on top.

But `_userTagTree` in 2.1 removed this if loop, see [dae-browser.py#L883](https://github.com/dae/anki/blob/master/aqt/browser.py#L883).

I think the 2.0 solution was better. Leeches are a problem so they should be more visible. As far as I see in 2.1 there's no prominent place for leeches - there's also nothing in the _cardStateFilters for the drop-down menu "Filters" next to the browser.searchEdit.lineEdit.

**Comment by lovac42** [comment]
You can use "tag:leech" and save as Fav or use customize sidebar addon. That was my reasoning at the time of adding that.

**Comment by ijgnd** [comment]
Thanks for the quick reply. I didn't know that this was intentional. My post was caused by a [reddit thread](
https://www.reddit.com/r/Anki/comments/e3k21b/leech_tag_in_21_missing_from_browser/) where someone complains that the leech tag disappeared from the sidebar in 2.1.  I know you can do it manually but it's so easy to miss and leeches are a problem in general ...
