### ISSUE TITLE
Incompatible with 2.1.17 beta 3

### ISSUE THREAD

**Issue by Cupbox** [lovac42/Blitzkrieg#8]
According to the [beta](https://apps.ankiweb.net/docs/beta.html) page, "add-on authors will need to modify their code to work with the new implementation. "

Debug info:
Anki 2.1.17 (da942617) Python 3.8.0 Qt 5.14.0 PyQt 5.13.2
Platform: Windows 10
Flags: frz=True ao=True sv=2

Caught exception:
Traceback (most recent call last):
  File "aqt\progress.py", line 72, in handler
  File "aqt\browser.py", line 1001, in deferredDisplay
  File "C:\Users\John Smith\AppData\Roaming\Anki2\addons21\564851917\main.py", line 26, in replace_buildTree
    self.sidebarTree.clear()
RuntimeError: wrapped C/C++ object of type SidebarTreeView has been deleted

**Comment by lovac42** [comment]
Yeah I just looked though the code changes too. Looks like it will require a complete rewrite or at lease half of it.

**Comment by Cupbox** [comment]
Ouch.

**Comment by lovac42** [comment]
Testers wanted: https://github.com/lovac42/Blitzkrieg/releases/tag/v0.1.0

**Comment by Cupbox** [comment]
It does seem slower now. I notice a delay on focusing elements sometimes. And after a tag is expanded, you cannot scroll for a second or so.

**Comment by lovac42** [comment]
Just released beta2 fixed the slowdown issue.

**Comment by Cupbox** [comment]
Yep. The speed issue seems to be fixed. The scrolling freeze on tag expansion that I mentioned earlier persists.

**Comment by lovac42** [comment]
I didn't experience any freezing on any of my systems. Maybe you have specially long subtags or some sort of conflict? Does it freeze without this addon when you expand/collapse subdecks? Could you test this with a new profile?

**Comment by Cupbox** [comment]
I've been trying to reproduce this the past few days but failing. I'm assuming my laptop's poor specifications were giving me the issue in question.
Sorry for wasting your time.
